spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/onboarding_dev
    username: onboardDev
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MariaDB103Dialect

  redis:
    host: localhost
    port: 6379
    password: "onboardRedis"
    lettuce:
      pool:
        max-active: 10
        max-idle: 5
        min-idle: 1
        time-between-eviction-runs: 5000


logging:
  level:
    me:
      hounds:
        wanted:
          onboarding: info